# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CloudOclusionReport
                                 A QGIS plugin
 Cloud Oclusion Report
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-06-12
        copyright            : (C) 2023 by CloudOclusionReport
        email                : CloudOclusionReport@email.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CloudOclusionReport class from file CloudOclusionReport.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .cloud_oclusion_report import CloudOclusionReport
    return CloudOclusionReport(iface)
