# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CloudOclusionReportDialog
                                 A QGIS plugin
 Cloud Oclusion Report
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-06-12
        git sha              : $Format:%H$
        copyright            : (C) 2023 by CloudOclusionReport
        email                : CloudOclusionReport@email.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.core import QgsProject, QgsMapLayerProxyModel
from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'cloud_oclusion_report_dialog_base.ui'))


class CloudOclusionReportDialog(QtWidgets.QDialog, FORM_CLASS):

    def __init__(self, parent=None):
        """Constructor."""
        super(CloudOclusionReportDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.evaluate_bt.clicked.connect(self.get_oclusion_result)
        self.ok_bt.clicked.connect(self.get_input_data)

    # self.aglomerateList = [om, numero_relatorio, bloco, periodo_mes, periodo_ano, endingDate, conformity,
    #                        analisysAnswer, nome_avaliador, nome_responsavel_tecnico, doc_date]
    # QgsProject.instance().mapLayersByName('edicao_area_sem_dados_a')[0]

    def get_data(self):
        teste = self.om_cb.currentText()
        print(teste)
        return teste

    def get_layer_name(self, layer):
        # for layer in QgsProject.instance().mapLayers().values():
        return layer.name()

    def filter_by_oclusion(self):
        #analisysDict[texto_edicao].append(area_oclusao)
        nonconforming = []
        conforming = []
        analisysDict = dict()

        for feature in QgsProject.instance().mapLayersByName('edicao_area_sem_dados_a')[0].getFeatures():
            texto_edicao = feature['texto_edicao']
            area_oclusao = feature['area_oclusao']
            try:
                analisysDict[texto_edicao].append(area_oclusao)
            except:
                analisysDict[texto_edicao] = [area_oclusao]

        for key in analisysDict:
            if max(analisysDict[key]) >= 0.2:
                nonconforming.append(key)
            else:
                conforming.append(key)

        # # GERAR RESULTADO
        #
        # if bloco in blockFail:
        #     analisysAnswer = 'Foram identificadas nuvens ou oclusões com área maior ou igual a 0,2 km².'
        #     conformity = 'Não Conforme'
        # else:
        #     analisysAnswer = 'Não foram identificadas nuvens ou oclusões com área maior ou igual a 0,2 km².'
        #     conformity = 'Conforme'
        #
        # self.aglomerateList = [om, numero_relatorio, bloco, periodo_mes, periodo_ano, endingDate, conformity,
        #                        analisysAnswer, nome_avaliador, nome_responsavel_tecnico, doc_date]

        print(analisysDict)
        print(conforming, nonconforming)
        return conforming, nonconforming

    def get_oclusion_result(self):

        conforming, nonconforming = self.filter_by_oclusion()

        if self.block_cb.currentText() in nonconforming:
            analisysAnswer = 'Foram identificadas nuvens ou oclusões com área maior ou igual a 0,2 km².'
            conformity = 'Não Conforme'
        else:
            analisysAnswer = 'Não foram identificadas nuvens ou oclusões com área maior ou igual a 0,2 km².'
            conformity = 'Conforme'

        return analisysAnswer, conformity

    def get_input_data(self):

        analisysAnswer, conformity = self.get_oclusion_result()

        print([self.om_cb.currentText(),self.report_number_le.text(),self.block_cb.currentText(),self.month_cb.currentText(),self.year_cb.currentText(),self.finish_date_le.text(),
        conformity, analisysAnswer, self.evaluator_name_le.text(), self.manager_le.text(), self.report_date_le.text()])
        return [self.om_cb.currentText(),self.report_number_le.text(),self.block_cb.currentText(),self.month_cb.currentText(),self.year_cb.currentText(),self.finish_date_le.text(),
        conformity, analisysAnswer, self.evaluator_name_le.text(), self.manager_le.text(), self.report_date_le.text()]
